name: Deploy to QuantCDN

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run build --if-present
    - run: npm test

    - uses: actions/upload-artifact@v2
      with:
        name: vuepress-build
        path: src/.vuepress/dist

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: vuepress-build
      - uses: quantcdn/deploy-action@v1
        with:
          customer: quant
          project: vuepress-example
          token: $({ secrets.QUANT_TOKEN })
          dir: src/.vuepress/dist
